# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/app_starter_gui',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/app_starter_gui',
                'lib_path': 'app_starter_gui'},
  'syms': { 'app_starter_gui.core': { 'app_starter_gui.core.Button': ('core.html#button', 'app_starter_gui/core.py'),
                                      'app_starter_gui.core.load_buttons': ('core.html#load_buttons', 'app_starter_gui/core.py'),
                                      'app_starter_gui.core.save_buttons': ('core.html#save_buttons', 'app_starter_gui/core.py'),
                                      'app_starter_gui.core.test_save_load': ('core.html#test_save_load', 'app_starter_gui/core.py')},
            'app_starter_gui.css': { 'app_starter_gui.css.generate_css': ('css.html#generate_css', 'app_starter_gui/css.py'),
                                     'app_starter_gui.css.test_generate_css': ('css.html#test_generate_css', 'app_starter_gui/css.py')},
            'app_starter_gui.gradio_app': { 'app_starter_gui.gradio_app.create_app': ( 'gradio_app.html#create_app',
                                                                                       'app_starter_gui/gradio_app.py'),
                                            'app_starter_gui.gradio_app.test_create_app': ( 'gradio_app.html#test_create_app',
                                                                                            'app_starter_gui/gradio_app.py')}}}
