"""Creation of the Gradio GUI for the app"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_gradio_app.ipynb.

# %% auto 0
__all__ = ['create_app', 'test_create_app']

# %% ../nbs/02_gradio_app.ipynb 2
import gradio as gr
from .core import Button, load_buttons
from .css import generate_css

# %% ../nbs/02_gradio_app.ipynb 4
def create_app(yaml_file='buttons.yaml', css_generator=generate_css):
    """Create a Gradio dashboard for the button interface
    
    Args:
        yaml_file: Path to YAML file containing button data (default: 'buttons.yaml')
        css_generator: Function to generate CSS (default: generate_css)
    Returns:
        gr.Blocks: Gradio interface
    """
    buttons = load_buttons(yaml_file)
    css = generate_css(buttons)
    
    with gr.Blocks(css=css) as blocks:
        with gr.Column():
            gr.HTML('<div class="button-grid">' + 
                   ''.join([f'''
                   <a href="{b.link_url}" class="{b.app_type.lower()}">
                       <img src="{b.image_url}" style="max-width:100%"/>
                       <p>{b.label}</p>
                   </a>''' for b in buttons]) +
                   '</div>')
    return blocks

# %% ../nbs/02_gradio_app.ipynb 6
from fastcore.test import *

def test_create_app():
    "Test app creation with example buttons"
    app = create_app('test_buttons.yaml')
    test(app, gr.Blocks, isinstance)
    
test_create_app()
